### ISSUE TITLE
no-week2 dir

### ISSUE THREAD

**Issue by MisooKim2** [seoojunn/C202309#1]
week2 폴더를 weak2 폴더로 만들어서 week2 폴더 없다고 식별됨.
폴더 내 파일 확인 불가능. 

weak2 폴더 이름 변경 후, 실습 파일 작성 및 저장 후,  다시 푸시 필요

또한 jnu 포털 파이썬 이클래스 과제에 본인 계정 업로드 바람

**Comment by seoojunn** [comment]
#1
