### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [seoojunn/C202309#4]
### 없는 PDF 파일
- project/week8/todo_manager.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

**Comment by seoojunn** [comment]
파일 이름 todo_manger.pdf -> todo_manager.pdf로 수정해서 재 커밋 했습니다


#4
